<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SESMT.API\SESMT.API.csproj" />
    <ProjectReference Include="..\SESMT.Application\SESMT.Application.csproj" />
    <ProjectReference Include="..\SESMT.Domain\SESMT.Domain.csproj" />
    <ProjectReference Include="..\SESMT.Infrastructure\SESMT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Architecture\" />
    <Folder Include="Integration\API\" />
    <Folder Include="Integration\Identity\" />
    <Folder Include="Integration\Messaging\" />
    <Folder Include="Integration\Persistence\" />
    <Folder Include="Unit\" />
  </ItemGroup>

</Project>